/*2026-03-11T20:21:32.128904600Z*/

/**********************************************************************************************************************
 * block.c
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 *
 * with extra comments for :
 *   Code     = true
 *   Location = true
 *
 * with optimizations for :
 *   Indexing = true
 *   Parenth. = true (Misra compatible)
 *   Id. len  = -1
 *   Tab size = 4
 *   Line len = 120
 **********************************************************************************************************************/

#include "block.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ALGOSTRUCT  BlockState_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c


/**********************************************************************************************************************
 * Prototypes
 **********************************************************************************************************************/
static void Recalibrate(ALGOSTRUCT *instance);
static void Reinitialize(ALGOSTRUCT *instance);
static void Startup(ALGOSTRUCT *instance);
static void DoStep(ALGOSTRUCT *instance);

/**********************************************************************************************************************
 * User function(s)
 **********************************************************************************************************************/
static void Recalibrate(ALGOSTRUCT *instance)
{
    /* Algorithm */
    /*
    Initialize variables with start value equation (dependent initializations):
    */

    instance->imLeadLag_T1 = instance->T1;

    instance->imLeadLag_T2 = instance->T2;

    instance->imLeadLag_TF_b[0] = instance->imLeadLag_K * instance->imLeadLag_T1;

    instance->imLeadLag_TF_b[1] = instance->imLeadLag_K;

    instance->imLeadLag_T2_dummy = SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->imLeadLag_T1 \
        - instance->imLeadLag_T2), 2.22044604925031308e-16) ? 1.0e+3 : instance->imLeadLag_T2;

    instance->imLeadLag_TF_a[0] = instance->imLeadLag_T2_dummy;

    instance->imLeadLag_TF_y_start = instance->imLeadLag_y_start;

    instance->imLeadLag_TF_bb[0] = instance->imLeadLag_TF_b[0];

    instance->imLeadLag_TF_bb[1] = instance->imLeadLag_TF_b[1];

    instance->imLeadLag_TF_d = instance->imLeadLag_TF_bb[0] / instance->imLeadLag_TF_a[0];

    instance->imLeadLag1_T1 = instance->T3;

    instance->imLeadLag1_T2 = instance->T4;

    instance->imLeadLag1_TF_b[0] = instance->imLeadLag1_K * instance->imLeadLag1_T1;

    instance->imLeadLag1_TF_b[1] = instance->imLeadLag1_K;

    instance->imLeadLag1_T2_dummy = SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->imLeadLag1_T1 \
        - instance->imLeadLag1_T2), 2.22044604925031308e-16) ? 1.0e+3 : instance->imLeadLag1_T2;

    instance->imLeadLag1_TF_a[0] = instance->imLeadLag1_T2_dummy;

    instance->imLeadLag1_TF_y_start = instance->imLeadLag1_y_start;

    instance->imLeadLag1_TF_bb[0] = instance->imLeadLag1_TF_b[0];

    instance->imLeadLag1_TF_bb[1] = instance->imLeadLag1_TF_b[1];

    instance->imLeadLag1_TF_d = instance->imLeadLag1_TF_bb[0] / instance->imLeadLag1_TF_a[0];

    instance->limiter_uMax = instance->vsmax;

    instance->limiter_uMin = instance->vsmin;

    instance->dLHPFreplacement_Kw = instance->Kw;

    instance->dLHPFreplacement_scaling_factor = instance->dLHPFreplacement_Kw;

    instance->dLHPFreplacement_highPassFilter_y_start = instance->dLHPFreplacement_y_start / SPE_rmax_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->dLHPFreplacement_scaling_factor), \
        2.22044604925031308e-16);

    instance->dLHPFreplacement_matchGain_k = instance->dLHPFreplacement_scaling_factor;
}

static void Reinitialize(ALGOSTRUCT *instance)
{
    /* Local variable(s) */
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c dLHPFreplacement_highPassFilter_uu[2];
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c dLHPFreplacement_highPassFilter_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_u;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_TF_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_TF_y;

    /* Algorithm */
    /*
    Initialize variables without explicit start value or equation (implicit initializations):
    */

    instance->der_dLHPFreplacement_highPassFilter_x_1 = 0.0;

    instance->der_imLeadLag_TF_x_scaled_1 = 0.0;

    instance->der_imLeadLag1_TF_x_scaled_1 = 0.0;

    /*
    Initialize variables with start value equation (dependent initializations):
    */

    dLHPFreplacement_highPassFilter_uu[0] = instance->vSI / instance->dLHPFreplacement_highPassFilter_u_nominal;

    dLHPFreplacement_highPassFilter_y = instance->dLHPFreplacement_highPassFilter_y_start;

    dLHPFreplacement_highPassFilter_uu[1] = dLHPFreplacement_highPassFilter_y / (instance->dLHPFreplacement_highPassFilter_gain \
        * instance->dLHPFreplacement_highPassFilter_u_nominal);

    instance->dLHPFreplacement_highPassFilter_x[0] = dLHPFreplacement_highPassFilter_uu[0] - dLHPFreplacement_highPassFilter_uu[1];

    imLeadLag_u = instance->dLHPFreplacement_matchGain_k * dLHPFreplacement_highPassFilter_y;

    imLeadLag_TF_y = instance->imLeadLag_TF_y_start;

    instance->imLeadLag_TF_x_scaled[0] = ((instance->imLeadLag_TF_d * imLeadLag_u) - imLeadLag_TF_y) / (instance->imLeadLag_TF_d \
        - instance->imLeadLag_TF_bb[1]);

    imLeadLag_y = SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->imLeadLag_T1 \
        - instance->imLeadLag_T2), 2.22044604925031308e-16) ? (instance->imLeadLag_K * imLeadLag_u) : imLeadLag_TF_y;

    imLeadLag1_TF_y = instance->imLeadLag1_TF_y_start;

    instance->imLeadLag1_TF_x_scaled[0] = ((instance->imLeadLag1_TF_d * imLeadLag_y) - imLeadLag1_TF_y) / (instance->imLeadLag1_TF_d \
        - instance->imLeadLag1_TF_bb[1]);

    imLeadLag1_y = SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->imLeadLag1_T1 \
        - instance->imLeadLag1_T2), 2.22044604925031308e-16) ? (instance->imLeadLag1_K * imLeadLag_y) : imLeadLag1_TF_y;

    instance->vs = SPE_greater_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMax) ? instance->limiter_uMax : SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMin) ? instance->limiter_uMin : imLeadLag1_y;

    /* Conduct delta(t) = 0 super-dense time initialization at next sampling:: */

    instance->discrete_stepSize_active = false;
}

static void Startup(ALGOSTRUCT *instance)
{
    /* Algorithm */
    /* ********************************************************************************************** Initialize constants: */
    /*
    Initialize variables without explicit start value or equation (implicit initializations):
    */

    instance->dLHPFreplacement_highPassFilter_r[0] = 0.0;

    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->discrete_stepSize = 1.00000000000000002e-3;

    instance->dLHPFreplacement_highPassFilter_u_nominal = 1.0;

    instance->dLHPFreplacement_highPassFilter_gain = 1.0;

    instance->imLeadLag_K = 1.0;

    instance->imLeadLag1_K = 1.0;

    instance->dLHPFreplacement_y_start = 0.0;

    instance->imLeadLag1_y_start = 0.0;

    instance->imLeadLag_y_start = 0.0;

    /* ******************************************************* Default initialize tuneable parameters (based on constants): */
    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->Kw = 1.08000000000000007e+1;

    instance->vsmin = 0.0;

    instance->vsmax = 3.29999999999999982;

    instance->T4 = 5.51479681529786006e-2;

    instance->T3 = 2.78203917593163985e-1;

    instance->T2 = 5.51479681529786006e-2;

    instance->T1 = 2.78203917593163985e-1;

    instance->vSI_start = 1.0;

    /* ****************************** Default initialize dependend parameters (based on constants and tuneable parameters): */

    Recalibrate(instance);

    /* ***************************************************** Default initialize inputs (based on constants and parameters): */
    /*
    Initialize variables with start value equation (dependent initializations):
    */

    instance->vSI = instance->vSI_start;

    /* ********************************* Default initialize states and outputs (based on constants, parameters and inputs): */

    Reinitialize(instance);
}

static void DoStep(ALGOSTRUCT *instance)
{
    /* Local variable(s) */
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c dLHPFreplacement_highPassFilter_uu[2];
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c dLHPFreplacement_highPassFilter_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_u;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_TF_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_y;
    SPE_Real_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_TF_y;

    /* Algorithm */
    if(instance->discrete_stepSize_active) {
        /* *********************************************************************** Update-equations for inline integration: */

        instance->dLHPFreplacement_highPassFilter_x[0] += instance->discrete_stepSize * instance->der_dLHPFreplacement_highPassFilter_x_1;

        instance->imLeadLag_TF_x_scaled[0] += instance->discrete_stepSize * instance->der_imLeadLag_TF_x_scaled_1;

        instance->imLeadLag1_TF_x_scaled[0] += instance->discrete_stepSize * instance->der_imLeadLag1_TF_x_scaled_1;
    } else {
        /* no action */;
    }

    /* ******************************************************************************************* Inline integration loop: */

    dLHPFreplacement_highPassFilter_uu[0] = instance->vSI / instance->dLHPFreplacement_highPassFilter_u_nominal;

    instance->der_dLHPFreplacement_highPassFilter_x_1 = instance->dLHPFreplacement_highPassFilter_r[0] * (instance->dLHPFreplacement_highPassFilter_x[0] \
        - dLHPFreplacement_highPassFilter_uu[0]);

    dLHPFreplacement_highPassFilter_uu[1] = dLHPFreplacement_highPassFilter_uu[0] - instance->dLHPFreplacement_highPassFilter_x[0];

    dLHPFreplacement_highPassFilter_y = instance->dLHPFreplacement_highPassFilter_gain * instance->dLHPFreplacement_highPassFilter_u_nominal \
        * dLHPFreplacement_highPassFilter_uu[1];

    imLeadLag_u = instance->dLHPFreplacement_matchGain_k * dLHPFreplacement_highPassFilter_y;

    instance->der_imLeadLag_TF_x_scaled_1 = (imLeadLag_u - instance->imLeadLag_TF_x_scaled[0]) / instance->imLeadLag_TF_a[0];

    imLeadLag_TF_y = ((instance->imLeadLag_TF_bb[1] - instance->imLeadLag_TF_d) * instance->imLeadLag_TF_x_scaled[0]) + \
        (instance->imLeadLag_TF_d * imLeadLag_u);

    imLeadLag_y = SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->imLeadLag_T1 \
        - instance->imLeadLag_T2), 2.22044604925031308e-16) ? (instance->imLeadLag_K * imLeadLag_u) : imLeadLag_TF_y;

    instance->der_imLeadLag1_TF_x_scaled_1 = (imLeadLag_y - instance->imLeadLag1_TF_x_scaled[0]) / instance->imLeadLag1_TF_a[0];

    /* ******************************************************************************** Inline integration post-processing: */

    imLeadLag1_TF_y = ((instance->imLeadLag1_TF_bb[1] - instance->imLeadLag1_TF_d) * instance->imLeadLag1_TF_x_scaled[0]) \
        + (instance->imLeadLag1_TF_d * imLeadLag_y);

    imLeadLag1_y = SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->imLeadLag1_T1 \
        - instance->imLeadLag1_T2), 2.22044604925031308e-16) ? (instance->imLeadLag1_K * imLeadLag_y) : imLeadLag1_TF_y;

    instance->vs = SPE_greater_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMax) ? instance->limiter_uMax : SPE_less_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMin) ? instance->limiter_uMin : imLeadLag1_y;

    instance->discrete_stepSize_active = true;
}

/**********************************************************************************************************************
 * init
 **********************************************************************************************************************/
void Startup_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    Startup(instance);
}

/**********************************************************************************************************************
 * step
 **********************************************************************************************************************/
void DoStep_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    DoStep(instance);
}

/**********************************************************************************************************************
 * recalibrate
 **********************************************************************************************************************/
void Recalibrate_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) \
    {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    Recalibrate(instance);
}

/**********************************************************************************************************************
 * reinitialize
 **********************************************************************************************************************/
void Reinitialize_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) \
    {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_Ha7cb37a433f18e8802317f9a0017ef7e53a577cd_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    Reinitialize(instance);
}

#ifdef __cplusplus
}
#endif

/* end of file */
