/*2026-03-16T02:00:46.461135400Z*/

/**********************************************************************************************************************
 * block.c
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 *
 * with extra comments for :
 *   Code     = true
 *   Location = true
 *
 * with optimizations for :
 *   Indexing = true
 *   Parenth. = true (Misra compatible)
 *   Id. len  = -1
 *   Tab size = 4
 *   Line len = 120
 **********************************************************************************************************************/

#include "block.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ALGOSTRUCT  BlockState_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed


/**********************************************************************************************************************
 * Prototypes
 **********************************************************************************************************************/
static void Recalibrate(ALGOSTRUCT *instance);
static void Reinitialize(ALGOSTRUCT *instance);
static void Startup(ALGOSTRUCT *instance);
static void DoStep(ALGOSTRUCT *instance);

/**********************************************************************************************************************
 * User function(s)
 **********************************************************************************************************************/
static void Recalibrate(ALGOSTRUCT *instance)
{
    /* Algorithm */
    /*
    Initialize variables with start value equation (dependent initializations):
    */

    instance->imLeadLag_T1 = instance->T1;

    instance->imLeadLag_T2 = instance->T2;

    instance->imLeadLag_TF_b[0] = instance->imLeadLag_K * instance->imLeadLag_T1;

    instance->imLeadLag_TF_b[1] = instance->imLeadLag_K;

    instance->imLeadLag_T2_dummy = SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        SPE_absolute_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(instance->imLeadLag_T1 \
        - instance->imLeadLag_T2), 2.22044604925031308e-16) ? 1.0e+3 : instance->imLeadLag_T2;

    instance->imLeadLag_TF_a[0] = instance->imLeadLag_T2_dummy;

    instance->imLeadLag_TF_y_start = instance->imLeadLag_y_start;

    instance->imLeadLag_TF_bb[0] = instance->imLeadLag_TF_b[0];

    instance->imLeadLag_TF_bb[1] = instance->imLeadLag_TF_b[1];

    instance->imLeadLag_TF_d = instance->imLeadLag_TF_bb[0] / instance->imLeadLag_TF_a[0];

    instance->imLeadLag1_T1 = instance->T3;

    instance->imLeadLag1_T2 = instance->T4;

    instance->imLeadLag1_TF_b[0] = instance->imLeadLag1_K * instance->imLeadLag1_T1;

    instance->imLeadLag1_TF_b[1] = instance->imLeadLag1_K;

    instance->imLeadLag1_T2_dummy = SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        SPE_absolute_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(instance->imLeadLag1_T1 \
        - instance->imLeadLag1_T2), 2.22044604925031308e-16) ? 1.0e+3 : instance->imLeadLag1_T2;

    instance->imLeadLag1_TF_a[0] = instance->imLeadLag1_T2_dummy;

    instance->imLeadLag1_TF_y_start = instance->imLeadLag1_y_start;

    instance->imLeadLag1_TF_bb[0] = instance->imLeadLag1_TF_b[0];

    instance->imLeadLag1_TF_bb[1] = instance->imLeadLag1_TF_b[1];

    instance->imLeadLag1_TF_d = instance->imLeadLag1_TF_bb[0] / instance->imLeadLag1_TF_a[0];

    instance->limiter_uMax = instance->vsmax;

    instance->limiter_uMin = instance->vsmin;

    instance->lpf_freqHz = instance->freqLow;

    instance->lpf_K = instance->kLPF;

    instance->lpf_T = 1.0 / (6.28318530717958623 * instance->lpf_freqHz);

    instance->dLHPFreplacement_Kw = instance->Kw;

    instance->dLHPFreplacement_Tw = instance->Tw;

    instance->dLHPFreplacement_K = instance->dLHPFreplacement_Kw * instance->dLHPFreplacement_Tw;

    instance->dLHPFreplacement_T = instance->dLHPFreplacement_Tw;
}

static void Reinitialize(ALGOSTRUCT *instance)
{
    /* Local variable(s) */
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag_u;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag_TF_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag1_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag1_TF_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed lpf_y;

    /* Algorithm */
    /*
    Initialize variables without explicit start value or equation (implicit initializations):
    */

    instance->der_imLeadLag_TF_x_scaled_1 = 0.0;

    instance->der_imLeadLag1_TF_x_scaled_1 = 0.0;

    /*
    Initialize variables with start value equation (dependent initializations):
    */

    instance->der_lpf_x = 0.0;

    instance->der_dLHPFreplacement_x = 0.0;

    instance->lpf_x = (instance->vSI * instance->lpf_T) / instance->lpf_T;

    lpf_y = instance->lpf_K * instance->lpf_x;

    instance->dLHPFreplacement_x = (lpf_y * instance->dLHPFreplacement_T) / instance->dLHPFreplacement_T;

    imLeadLag_u = (instance->dLHPFreplacement_K * (lpf_y - instance->dLHPFreplacement_x)) / instance->dLHPFreplacement_T;

    imLeadLag_TF_y = instance->imLeadLag_TF_y_start;

    instance->imLeadLag_TF_x_scaled[0] = ((instance->imLeadLag_TF_d * imLeadLag_u) - imLeadLag_TF_y) / (instance->imLeadLag_TF_d \
        - instance->imLeadLag_TF_bb[1]);

    imLeadLag_y = SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        SPE_absolute_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(instance->imLeadLag_T1 \
        - instance->imLeadLag_T2), 2.22044604925031308e-16) ? (instance->imLeadLag_K * imLeadLag_u) : imLeadLag_TF_y;

    imLeadLag1_TF_y = instance->imLeadLag1_TF_y_start;

    instance->imLeadLag1_TF_x_scaled[0] = ((instance->imLeadLag1_TF_d * imLeadLag_y) - imLeadLag1_TF_y) / (instance->imLeadLag1_TF_d \
        - instance->imLeadLag1_TF_bb[1]);

    imLeadLag1_y = SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        SPE_absolute_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(instance->imLeadLag1_T1 \
        - instance->imLeadLag1_T2), 2.22044604925031308e-16) ? (instance->imLeadLag1_K * imLeadLag_y) : imLeadLag1_TF_y;

    instance->vs = SPE_greater_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMax) ? instance->limiter_uMax : SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMin) ? instance->limiter_uMin : imLeadLag1_y;

    /* Conduct delta(t) = 0 super-dense time initialization at next sampling:: */

    instance->discrete_stepSize_active = false;
}

static void Startup(ALGOSTRUCT *instance)
{
    /* Algorithm */
    /* ********************************************************************************************** Initialize constants: */
    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->discrete_stepSize = 1.00000000000000002e-3;

    instance->imLeadLag_K = 1.0;

    instance->imLeadLag1_K = 1.0;

    instance->imLeadLag1_y_start = 0.0;

    instance->imLeadLag_y_start = 0.0;

    /* ******************************************************* Default initialize tuneable parameters (based on constants): */
    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->Tw = 2.5e-1;

    instance->Kw = 4.45;

    instance->kLPF = 1.0;

    instance->freqLow = 5.0;

    instance->vsmin = -1.5;

    instance->vsmax = 1.5;

    instance->T4 = 5.56202789619913984e-2;

    instance->T3 = 3.24178742588019986e-1;

    instance->T2 = 5.56202789619913984e-2;

    instance->T1 = 3.24178742588019986e-1;

    instance->vSI_start = 1.0;

    /* ****************************** Default initialize dependend parameters (based on constants and tuneable parameters): */

    Recalibrate(instance);

    /* ***************************************************** Default initialize inputs (based on constants and parameters): */
    /*
    Initialize variables with start value equation (dependent initializations):
    */

    instance->vSI = instance->vSI_start;

    /* ********************************* Default initialize states and outputs (based on constants, parameters and inputs): */

    Reinitialize(instance);
}

static void DoStep(ALGOSTRUCT *instance)
{
    /* Local variable(s) */
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag_u;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag_TF_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag1_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed imLeadLag1_TF_y;
    SPE_Real_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed lpf_y;

    /* Algorithm */
    if(instance->discrete_stepSize_active) {
        /* *********************************************************************** Update-equations for inline integration: */

        instance->lpf_x += instance->discrete_stepSize * instance->der_lpf_x;

        instance->dLHPFreplacement_x += instance->discrete_stepSize * instance->der_dLHPFreplacement_x;

        instance->imLeadLag_TF_x_scaled[0] += instance->discrete_stepSize * instance->der_imLeadLag_TF_x_scaled_1;

        instance->imLeadLag1_TF_x_scaled[0] += instance->discrete_stepSize * instance->der_imLeadLag1_TF_x_scaled_1;
    } else {
        /* no action */;
    }

    /* ******************************************************************************************* Inline integration loop: */

    instance->der_lpf_x = (instance->vSI - instance->lpf_x) / instance->lpf_T;

    lpf_y = instance->lpf_K * instance->lpf_x;

    instance->der_dLHPFreplacement_x = (lpf_y - instance->dLHPFreplacement_x) / instance->dLHPFreplacement_T;

    imLeadLag_u = (instance->dLHPFreplacement_K * (lpf_y - instance->dLHPFreplacement_x)) / instance->dLHPFreplacement_T;

    instance->der_imLeadLag_TF_x_scaled_1 = (imLeadLag_u - instance->imLeadLag_TF_x_scaled[0]) / instance->imLeadLag_TF_a[0];

    imLeadLag_TF_y = ((instance->imLeadLag_TF_bb[1] - instance->imLeadLag_TF_d) * instance->imLeadLag_TF_x_scaled[0]) + \
        (instance->imLeadLag_TF_d * imLeadLag_u);

    imLeadLag_y = SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        SPE_absolute_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(instance->imLeadLag_T1 \
        - instance->imLeadLag_T2), 2.22044604925031308e-16) ? (instance->imLeadLag_K * imLeadLag_u) : imLeadLag_TF_y;

    instance->der_imLeadLag1_TF_x_scaled_1 = (imLeadLag_y - instance->imLeadLag1_TF_x_scaled[0]) / instance->imLeadLag1_TF_a[0];

    /* ******************************************************************************** Inline integration post-processing: */

    imLeadLag1_TF_y = ((instance->imLeadLag1_TF_bb[1] - instance->imLeadLag1_TF_d) * instance->imLeadLag1_TF_x_scaled[0]) \
        + (instance->imLeadLag1_TF_d * imLeadLag_y);

    imLeadLag1_y = SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        SPE_absolute_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(instance->imLeadLag1_T1 \
        - instance->imLeadLag1_T2), 2.22044604925031308e-16) ? (instance->imLeadLag1_K * imLeadLag_y) : imLeadLag1_TF_y;

    instance->vs = SPE_greater_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMax) ? instance->limiter_uMax : SPE_less_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(&instance->ErrorSignals, \
        imLeadLag1_y, instance->limiter_uMin) ? instance->limiter_uMin : imLeadLag1_y;

    instance->discrete_stepSize_active = true;
}

/**********************************************************************************************************************
 * init
 **********************************************************************************************************************/
void Startup_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(ALGOSTRUCT *instance) {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed;
    Startup(instance);
}

/**********************************************************************************************************************
 * step
 **********************************************************************************************************************/
void DoStep_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(ALGOSTRUCT *instance) {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed;
    DoStep(instance);
}

/**********************************************************************************************************************
 * recalibrate
 **********************************************************************************************************************/
void Recalibrate_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(ALGOSTRUCT *instance) \
    {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed;
    Recalibrate(instance);
}

/**********************************************************************************************************************
 * reinitialize
 **********************************************************************************************************************/
void Reinitialize_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(ALGOSTRUCT *instance) \
    {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed;
    Reinitialize(instance);
}

#ifdef __cplusplus
}
#endif

/* end of file */
