/*2026-03-13T20:58:45.227757800Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_BLOCK_H225C1BAF6CF5A31BC9B0C38998C32298F6F0531C_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H
#define MEI_BLOCK_INTERFACE_BLOCK_H225C1BAF6CF5A31BC9B0C38998C32298F6F0531C_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

typedef int MODELICA_Boolean;
typedef int MODELICA_Integer;
typedef double MODELICA_Real;

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
/* return new instance */
extern void *mei_Startup_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  (void);
/* destroy instance */
extern void  mei_Terminate_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void* object);
/* perform simulation step */
extern MODELICA_Integer mei_DoStep_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  \
     (void* object
,   /* IN */    MODELICA_Real   vSI
,   /* OUT */   MODELICA_Real*  vs
);

/* recalibrate parameters */
extern MODELICA_Integer mei_Recalibrate_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* TUNEABLE */  MODELICA_Real   Kw
,   /* TUNEABLE */  MODELICA_Real   T1
,   /* TUNEABLE */  MODELICA_Real   T2
,   /* TUNEABLE */  MODELICA_Real   T3
,   /* TUNEABLE */  MODELICA_Real   T4
,   /* TUNEABLE */  MODELICA_Real   Tw
,   /* TUNEABLE */  MODELICA_Real   freqLow
,   /* TUNEABLE */  MODELICA_Real   kLPF
,   /* TUNEABLE */  MODELICA_Real   vSI_start
,   /* TUNEABLE */  MODELICA_Real   vsmax
,   /* TUNEABLE */  MODELICA_Real   vsmin
);

/* reinitialize states and outputs */
extern MODELICA_Integer mei_Reinitialize_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* IN */    MODELICA_Real   vSI
,   /* OUT */   MODELICA_Real*  vs
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_BLOCK_H225C1BAF6CF5A31BC9B0C38998C32298F6F0531C_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H */
/* end of file */
