/*2026-03-11T19:05:43.621588200Z*/

/**********************************************************************************************************************
 * sii_block_interface.h
 *
 * Single internal instance.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 *
 * with calling convention :
 *   Arguments = global var (block_state_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed)
 *   Ret. type = bool
 *
 * with names :
 *   Init Fcn  = sii_Startup_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed
 *   Step Fcn  = sii_DoStep_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed
 *   Recal Fcn = sii_Recalibrate_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed
 *   Reinit Fcn = sii_Reinitialize_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed
 **********************************************************************************************************************/

#ifndef SII_BLOCK_INTERFACE_BLOCK_H225C1BAF6CF5A31BC9B0C38998C32298F6F0531C_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H
#define SII_BLOCK_INTERFACE_BLOCK_H225C1BAF6CF5A31BC9B0C38998C32298F6F0531C_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * code
 **********************************************************************************************************************/
extern bool sii_Startup_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void);
extern bool sii_DoStep_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void);
extern bool sii_Recalibrate_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void);

extern bool sii_Reinitialize_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void);
/**********************************************************************************************************************
 * data
 **********************************************************************************************************************/
extern BlockState_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed block_state_H225c1baf6cf5a31bc9b0c38998c32298f6f0531c_cb4a8a449b4ada864625ee5a4355578a3aaf08ed; \
    /* global memory storage */

#ifdef __cplusplus
}
#endif

#endif /* SII_BLOCK_INTERFACE_BLOCK_H225C1BAF6CF5A31BC9B0C38998C32298F6F0531C_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H */
/* end of file */
