/*2025-10-25T12:10:24.981209201Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_H0CD5E2FB2801360CEBB2E36F93C4A1B96253DCD5_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H
#define MEI_BLOCK_INTERFACE_H0CD5E2FB2801360CEBB2E36F93C4A1B96253DCD5_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H

#include <stdlib.h>
#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
extern void *mei_Startup_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c  (void)    \
         /* return new instance */;
extern void  mei_Terminate_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void* object) \
    /* destroy instance */;
extern int   mei_DoStep_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c   (void* object \
     /* perform simulation step */
,   /* IN */    double  vSI
,   /* OUT */   double* vs
);

extern int   mei_Recalibrate_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c   (void* \
    object  /* recalibrate parameters */
,   /* TUNEABLE */  double  Kw
,   /* TUNEABLE */  double  T1
,   /* TUNEABLE */  double  T2
,   /* TUNEABLE */  double  T3
,   /* TUNEABLE */  double  T4
,   /* TUNEABLE */  double  Tw
,   /* TUNEABLE */  double  vSI_start
,   /* TUNEABLE */  double  vsmax
,   /* TUNEABLE */  double  vsmin
);

extern int   mei_Reinitialize_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c   (void* \
    object  /* reinitialize states and outputs */
,   /* IN */    double  vSI
,   /* OUT */   double* vs
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_H0CD5E2FB2801360CEBB2E36F93C4A1B96253DCD5_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H */
/* end of file */
