/*2025-10-25T12:10:24.976790139Z*/

/**********************************************************************************************************************
 * sii_block_interface.h
 *
 * Single internal instance.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 *
 * with calling convention :
 *   Arguments = global var (block_state_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c)
 *   Ret. type = Boolean
 *
 * with names :
 *   Init Fcn  = sii_Startup_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Step Fcn  = sii_DoStep_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Recal Fcn = sii_Recalibrate_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Reinit Fcn = sii_Reinitialize_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 **********************************************************************************************************************/

#ifndef SII_BLOCK_INTERFACE_H0CD5E2FB2801360CEBB2E36F93C4A1B96253DCD5_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H
#define SII_BLOCK_INTERFACE_H0CD5E2FB2801360CEBB2E36F93C4A1B96253DCD5_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * code
 **********************************************************************************************************************/
extern Boolean sii_Startup_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
extern Boolean sii_DoStep_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
extern Boolean sii_Recalibrate_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);

extern Boolean sii_Reinitialize_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
/**********************************************************************************************************************
 * data
 **********************************************************************************************************************/
extern BlockState_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c block_state_H0cd5e2fb2801360cebb2e36f93c4a1b96253dcd5_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c; \
    /* global memory storage */

#ifdef __cplusplus
}
#endif

#endif /* SII_BLOCK_INTERFACE_H0CD5E2FB2801360CEBB2E36F93C4A1B96253DCD5_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H */
/* end of file */
