/*2025-12-22T20:20:43.537181330Z*/

/**********************************************************************************************************************
 * block.c
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 *
 * with extra comments for :
 *   Code     = true
 *   Location = true
 *
 * with optimizations for :
 *   Indexing = true
 *   Parenth. = true (Misra compatible)
 *   Id. len  = -1
 *   Tab size = 4
 *   Line len = 120
 **********************************************************************************************************************/

#include "block.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ALGOSTRUCT  BlockState_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c


/**********************************************************************************************************************
 * Prototypes
 **********************************************************************************************************************/
static void Recalibrate(ALGOSTRUCT *instance);
static void Reinitialize(ALGOSTRUCT *instance);
static void Startup(ALGOSTRUCT *instance);
static void DoStep(ALGOSTRUCT *instance);

/**********************************************************************************************************************
 * User function(s)
 **********************************************************************************************************************/
static void Recalibrate(ALGOSTRUCT *instance)
{
    /* Algorithm */
    /*
    Initialize variables with start value equation (dependent initializations):
    */

    instance->imLeadLag_TF_b[0] = instance->imLeadLag_K * instance->T1;

    instance->imLeadLag_TF_b[1] = instance->imLeadLag_K;

    instance->imLeadLag_T2_dummy = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->T1 - \
        instance->T2), 1.00000000000000008e-15) ? 1.0e+3 : instance->T2;

    instance->imLeadLag_TF_a[0] = instance->imLeadLag_T2_dummy;

    instance->imLeadLag_TF_x_start[0] = instance->imLeadLag_x_start;

    instance->imLeadLag_TF_bb[0] = instance->imLeadLag_TF_b[0];

    instance->imLeadLag_TF_bb[1] = instance->imLeadLag_TF_b[1];

    instance->imLeadLag_TF_d = instance->imLeadLag_TF_bb[0] / instance->imLeadLag_TF_a[0];

    instance->imLeadLag1_TF_b[0] = instance->imLeadLag1_K * instance->T3;

    instance->imLeadLag1_TF_b[1] = instance->imLeadLag1_K;

    instance->imLeadLag1_T2_dummy = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->T3 - \
        instance->T4), 1.00000000000000008e-15) ? 1.0e+3 : instance->T4;

    instance->imLeadLag1_TF_a[0] = instance->imLeadLag1_T2_dummy;

    instance->imLeadLag1_TF_x_start[0] = instance->imLeadLag1_x_start;

    instance->imLeadLag1_TF_bb[0] = instance->imLeadLag1_TF_b[0];

    instance->imLeadLag1_TF_bb[1] = instance->imLeadLag1_TF_b[1];

    instance->imLeadLag1_TF_d = instance->imLeadLag1_TF_bb[0] / instance->imLeadLag1_TF_a[0];

    instance->derivativeLag_K = instance->Kw * instance->Tw;

    instance->derivativeLag_K_dummy = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->derivativeLag_K), \
        1.00000000000000008e-15) ? 1.0 : instance->derivativeLag_K;

    instance->derivativeLag_TF_b[0] = instance->derivativeLag_K_dummy;

    instance->derivativeLag_T_dummy = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->Tw), \
        1.00000000000000008e-15) ? 1.0e+3 : instance->Tw;

    instance->derivativeLag_TF_a[0] = instance->derivativeLag_T_dummy;

    instance->derivativeLag_TF_x_start[0] = instance->derivativeLag_x_start;

    instance->derivativeLag_TF_bb[0] = instance->derivativeLag_TF_b[0];

    instance->derivativeLag_TF_d = instance->derivativeLag_TF_bb[0] / instance->derivativeLag_TF_a[0];
}

static void Reinitialize(ALGOSTRUCT *instance)
{
    /* Local variable(s) */
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c derivativeLag_TF_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_u;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_TF_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_TF_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c solution_buffer_for_x;

    /* Algorithm */
    /*
    Initialize variables without explicit start value or equation (implicit initializations):
    */

    instance->der_derivativeLag_TF_x_scaled_1 = 0.0;

    instance->der_imLeadLag_TF_x_scaled_1 = 0.0;

    instance->der_imLeadLag1_TF_x_scaled_1 = 0.0;

    /*
    Initialize variables with start value equation (dependent initializations):
    */

    derivativeLag_TF_y = instance->derivativeLag_y_start;

    solution_buffer_for_x = ((instance->derivativeLag_TF_d * instance->vSI) - derivativeLag_TF_y) / instance->derivativeLag_TF_d;

    if(SPE_isNan_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(solution_buffer_for_x) \
        || SPE_isInfinite_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(solution_buffer_for_x)) \
        {
        /* Set state to default start-value and signal error: */

        instance->derivativeLag_TF_x_scaled_1 = instance->derivativeLag_TF_x_start[0];

        instance->ErrorSignals |= SPE_ERRORSIGNAL_SOLVE_LINEAR_EQUATIONS_FAILED_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    } else {
        /* Only if the system can be solved, assign computed state: */

        instance->derivativeLag_TF_x_scaled_1 = solution_buffer_for_x;
    }

    imLeadLag_TF_y = instance->imLeadLag_y_start;

    imLeadLag_u = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->Tw), \
        1.00000000000000008e-15) ? instance->vSI : derivativeLag_TF_y;

    solution_buffer_for_x = ((instance->imLeadLag_TF_d * imLeadLag_u) - imLeadLag_TF_y) / (instance->imLeadLag_TF_d - instance->imLeadLag_TF_bb[1]);

    if(SPE_isNan_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(solution_buffer_for_x) \
        || SPE_isInfinite_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(solution_buffer_for_x)) \
        {
        /* Set state to default start-value and signal error: */

        instance->imLeadLag_TF_x_scaled_1 = instance->imLeadLag_TF_x_start[0];

        instance->ErrorSignals |= SPE_ERRORSIGNAL_SOLVE_LINEAR_EQUATIONS_FAILED_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    } else {
        /* Only if the system can be solved, assign computed state: */

        instance->imLeadLag_TF_x_scaled_1 = solution_buffer_for_x;
    }

    imLeadLag1_TF_y = instance->imLeadLag1_y_start;

    imLeadLag_y = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->T1 - \
        instance->T2), 1.00000000000000008e-15) ? (instance->imLeadLag_K * imLeadLag_u) : imLeadLag_TF_y;

    solution_buffer_for_x = ((instance->imLeadLag1_TF_d * imLeadLag_y) - imLeadLag1_TF_y) / (instance->imLeadLag1_TF_d \
        - instance->imLeadLag1_TF_bb[1]);

    if(SPE_isNan_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(solution_buffer_for_x) \
        || SPE_isInfinite_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(solution_buffer_for_x)) \
        {
        /* Set state to default start-value and signal error: */

        instance->imLeadLag1_TF_x_scaled_1 = instance->imLeadLag1_TF_x_start[0];

        instance->ErrorSignals |= SPE_ERRORSIGNAL_SOLVE_LINEAR_EQUATIONS_FAILED_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    } else {
        /* Only if the system can be solved, assign computed state: */

        instance->imLeadLag1_TF_x_scaled_1 = solution_buffer_for_x;
    }

    imLeadLag1_y = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->T3 - \
        instance->T4), 1.00000000000000008e-15) ? (instance->imLeadLag1_K * imLeadLag_y) : imLeadLag1_TF_y;

    instance->vs = SPE_greater_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->vsmax) ? instance->vsmax : SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->vsmin) ? instance->vsmin : imLeadLag1_y;
}

static void Startup(ALGOSTRUCT *instance)
{
    /* Algorithm */
    /* ********************************************************************************************** Initialize constants: */
    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->discrete_stepSize = 1.00000000000000002e-3;

    instance->imLeadLag_K = 1.0;

    instance->imLeadLag1_K = 1.0;

    instance->imLeadLag1_y_start = 0.0;

    instance->imLeadLag_y_start = 0.0;

    instance->derivativeLag_y_start = 0.0;

    instance->derivativeLag_x_start = 0.0;

    instance->imLeadLag1_x_start = 0.0;

    instance->imLeadLag_x_start = 0.0;

    /* ******************************************************* Default initialize tuneable parameters (based on constants): */
    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->Tw = 1.40999999999999992;

    instance->T1 = 1.53999999999999998e-1;

    instance->T2 = 3.30000000000000016e-2;

    instance->T3 = 1.0;

    instance->T4 = 1.0;

    instance->vsmax = 2.00000000000000011e-1;

    instance->vsmin = -0.200000000000000011;

    instance->Kw = 9.5;

    instance->vSI_start = 1.0;

    /* ****************************** Default initialize dependend parameters (based on constants and tuneable parameters): */

    Recalibrate(instance);

    /* ***************************************************** Default initialize inputs (based on constants and parameters): */
    /*
    Initialize variables with explicit start value (independent initializations):
    */

    instance->vSI = instance->vSI_start;

    /* ********************************* Default initialize states and outputs (based on constants, parameters and inputs): */

    Reinitialize(instance);
}

static void DoStep(ALGOSTRUCT *instance)
{
    /* Local variable(s) */
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c derivativeLag_TF_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_u;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag_TF_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_y;
    SPE_Real_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c imLeadLag1_TF_y;

    /* Algorithm */
    /* *************************************************************************** Update-equations for inline integration: */

    instance->derivativeLag_TF_x_scaled_1 += instance->discrete_stepSize * instance->der_derivativeLag_TF_x_scaled_1;

    instance->imLeadLag_TF_x_scaled_1 += instance->discrete_stepSize * instance->der_imLeadLag_TF_x_scaled_1;

    instance->imLeadLag1_TF_x_scaled_1 += instance->discrete_stepSize * instance->der_imLeadLag1_TF_x_scaled_1;

    /* ******************************************************************************************* Inline integration loop: */

    instance->der_derivativeLag_TF_x_scaled_1 = (instance->vSI - instance->derivativeLag_TF_x_scaled_1) / instance->derivativeLag_TF_a[0];

    derivativeLag_TF_y = (instance->derivativeLag_TF_d * instance->vSI) - (instance->derivativeLag_TF_d * instance->derivativeLag_TF_x_scaled_1);

    imLeadLag_u = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->Tw), \
        1.00000000000000008e-15) ? instance->vSI : derivativeLag_TF_y;

    instance->der_imLeadLag_TF_x_scaled_1 = (imLeadLag_u - instance->imLeadLag_TF_x_scaled_1) / instance->imLeadLag_TF_a[0];

    imLeadLag_TF_y = ((instance->imLeadLag_TF_bb[1] - instance->imLeadLag_TF_d) * instance->imLeadLag_TF_x_scaled_1) + \
        (instance->imLeadLag_TF_d * imLeadLag_u);

    imLeadLag_y = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->T1 - \
        instance->T2), 1.00000000000000008e-15) ? (instance->imLeadLag_K * imLeadLag_u) : imLeadLag_TF_y;

    instance->der_imLeadLag1_TF_x_scaled_1 = (imLeadLag_y - instance->imLeadLag1_TF_x_scaled_1) / instance->imLeadLag1_TF_a[0];

    /* ******************************************************************************** Inline integration post-processing: */

    imLeadLag1_TF_y = ((instance->imLeadLag1_TF_bb[1] - instance->imLeadLag1_TF_d) * instance->imLeadLag1_TF_x_scaled_1) \
        + (instance->imLeadLag1_TF_d * imLeadLag_y);

    imLeadLag1_y = SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        SPE_absolute_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(instance->T3 - \
        instance->T4), 1.00000000000000008e-15) ? (instance->imLeadLag1_K * imLeadLag_y) : imLeadLag1_TF_y;

    instance->vs = SPE_greater_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->vsmax) ? instance->vsmax : SPE_less_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(&instance->ErrorSignals, \
        imLeadLag1_y, instance->vsmin) ? instance->vsmin : imLeadLag1_y;
}

/**********************************************************************************************************************
 * init
 **********************************************************************************************************************/
void Startup_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    Startup(instance);
}

/**********************************************************************************************************************
 * step
 **********************************************************************************************************************/
void DoStep_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    DoStep(instance);
}

/**********************************************************************************************************************
 * recalibrate
 **********************************************************************************************************************/
void Recalibrate_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) \
    {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    Recalibrate(instance);
}

/**********************************************************************************************************************
 * reinitialize
 **********************************************************************************************************************/
void Reinitialize_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(ALGOSTRUCT *instance) \
    {
    instance->ErrorSignals = SPE_ERRORSIGNAL_NONE_He61c9e6d5af0d56a3b757d54a04e861698c3a4f4_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c;
    Reinitialize(instance);
}

#ifdef __cplusplus
}
#endif

/* end of file */
