/*2026-02-27T15:56:21.382527900Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_BLOCK_H216F2FD6BEE4C6CBC88940592D1C21EA8FCAA7B3_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H
#define MEI_BLOCK_INTERFACE_BLOCK_H216F2FD6BEE4C6CBC88940592D1C21EA8FCAA7B3_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

typedef int MODELICA_Boolean;
typedef int MODELICA_Integer;
typedef double MODELICA_Real;

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
/* return new instance */
extern void *mei_Startup_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  (void);
/* destroy instance */
extern void  mei_Terminate_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void* object);
/* perform simulation step */
extern MODELICA_Integer mei_DoStep_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  \
     (void* object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
);

/* recalibrate parameters */
extern MODELICA_Integer mei_Recalibrate_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* TUNEABLE */  MODELICA_Real   K0
);

/* reinitialize states and outputs */
extern MODELICA_Integer mei_Reinitialize_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_BLOCK_H216F2FD6BEE4C6CBC88940592D1C21EA8FCAA7B3_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H */
/* end of file */
