/*2026-01-14T20:53:28.962808544Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_BLOCK_H525B873079CF7A65F464C408F25344D5BD630CAB_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H
#define MEI_BLOCK_INTERFACE_BLOCK_H525B873079CF7A65F464C408F25344D5BD630CAB_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

typedef int MODELICA_Boolean;
typedef int MODELICA_Integer;
typedef double MODELICA_Real;

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
/* return new instance */
extern void *mei_Startup_H525b873079cf7a65f464c408f25344d5bd630cab_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  (void);
/* destroy instance */
extern void  mei_Terminate_H525b873079cf7a65f464c408f25344d5bd630cab_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void* object);
/* perform simulation step */
extern MODELICA_Integer mei_DoStep_H525b873079cf7a65f464c408f25344d5bd630cab_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  \
     (void* object
,   /* IN */    MODELICA_Real   vSI
,   /* OUT */   MODELICA_Real*  vs
);

/* recalibrate parameters */
extern MODELICA_Integer mei_Recalibrate_H525b873079cf7a65f464c408f25344d5bd630cab_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* TUNEABLE */  MODELICA_Real   Kw
,   /* TUNEABLE */  MODELICA_Real   T1
,   /* TUNEABLE */  MODELICA_Real   T2
,   /* TUNEABLE */  MODELICA_Real   T3
,   /* TUNEABLE */  MODELICA_Real   T4
,   /* TUNEABLE */  MODELICA_Real   Tw
,   /* TUNEABLE */  MODELICA_Real   vSI_start
,   /* TUNEABLE */  MODELICA_Real   vsmax
,   /* TUNEABLE */  MODELICA_Real   vsmin
);

/* reinitialize states and outputs */
extern MODELICA_Integer mei_Reinitialize_H525b873079cf7a65f464c408f25344d5bd630cab_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* IN */    MODELICA_Real   vSI
,   /* OUT */   MODELICA_Real*  vs
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_BLOCK_H525B873079CF7A65F464C408F25344D5BD630CAB_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H */
/* end of file */
