/*2026-03-26T03:11:17.002414800Z*/

/**********************************************************************************************************************
 * mei_block_interface.c
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#include "mei_block_interface.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>

#define ALGOSTRUCT  BlockState_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed

void *mei_Startup_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void) {
    ALGOSTRUCT* self = ((ALGOSTRUCT*) malloc(sizeof(ALGOSTRUCT)));
    if(self != NULL) {
        Startup_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(self);
    }
    return self;
}

void mei_Terminate_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void *object) {
    if(object != NULL) {
        free(object);
    }
}

MODELICA_Integer mei_DoStep_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void *object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Boolean    faultL1
,   /* IN */    MODELICA_Boolean    faultL2
,   /* IN */    MODELICA_Real   uPLoad
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
) {
    ALGOSTRUCT *self = (ALGOSTRUCT *) object;
    MODELICA_Integer result = -1;

    if(self != NULL) {
        self->fault = (0 != fault) ? 1 : 0;
        self->faultL1 = (0 != faultL1) ? 1 : 0;
        self->faultL2 = (0 != faultL2) ? 1 : 0;
        self->uPLoad = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) uPLoad;
        self->vf = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) vf;

        DoStep_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(self);

        *Pgen = ((MODELICA_Real) self->Pgen);
        *Qgen = ((MODELICA_Real) self->Qgen);
        *v = ((MODELICA_Real) self->v);
        *vf0OUT = ((MODELICA_Real) self->vf0OUT);
        *w = ((MODELICA_Real) self->w);
        result = ((MODELICA_Integer) self->ErrorSignals);
    }

    return result;
}

MODELICA_Integer mei_Recalibrate_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void \
    *object
,   /* TUNEABLE */  MODELICA_Real   K0
,   /* TUNEABLE */  MODELICA_Real   woffset
,   /* TUNEABLE */  MODELICA_Real   wscale
) {
    ALGOSTRUCT *self = (ALGOSTRUCT *) object;
    MODELICA_Integer result = -1;

    if(self != NULL) {
        self->K0 = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) K0;
        self->woffset = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) woffset;
        self->wscale = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) wscale;

        Recalibrate_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(self);

        result = ((MODELICA_Integer) self->ErrorSignals);
    }

    return result;
}

MODELICA_Integer mei_Reinitialize_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void \
    *object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Boolean    faultL1
,   /* IN */    MODELICA_Boolean    faultL2
,   /* IN */    MODELICA_Real   uPLoad
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
) {
    ALGOSTRUCT *self = (ALGOSTRUCT *) object;
    MODELICA_Integer result = -1;

    if(self != NULL) {
        self->fault = (0 != fault) ? 1 : 0;
        self->faultL1 = (0 != faultL1) ? 1 : 0;
        self->faultL2 = (0 != faultL2) ? 1 : 0;
        self->uPLoad = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) uPLoad;
        self->vf = (SPE_Real_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed) vf;

        Reinitialize_H96e4298bd9675fbbcb46b0c1f68b039a5627ebc5_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(self);

        *Pgen = ((MODELICA_Real) self->Pgen);
        *Qgen = ((MODELICA_Real) self->Qgen);
        *v = ((MODELICA_Real) self->v);
        *vf0OUT = ((MODELICA_Real) self->vf0OUT);
        *w = ((MODELICA_Real) self->w);
        result = ((MODELICA_Integer) self->ErrorSignals);
    }

    return result;
}

#ifdef __cplusplus
}
#endif

/* end of file */
