/*2026-02-27T15:56:24.293567500Z*/

/**********************************************************************************************************************
 * mei_block_interface.c
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#include "mei_block_interface.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>

#define ALGOSTRUCT  BlockState_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c

void *mei_Startup_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void) {
    ALGOSTRUCT* self = ((ALGOSTRUCT*) malloc(sizeof(ALGOSTRUCT)));
    if(self != NULL) {
        Startup_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(self);
    }
    return self;
}

void mei_Terminate_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void *object) {
    if(object != NULL) {
        free(object);
    }
}

MODELICA_Integer mei_DoStep_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void *object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
) {
    ALGOSTRUCT *self = (ALGOSTRUCT *) object;
    MODELICA_Integer result = -1;

    if(self != NULL) {
        self->fault = (0 != fault) ? 1 : 0;
        self->vf = (SPE_Real_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c) vf;

        DoStep_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(self);

        *Pgen = ((MODELICA_Real) self->Pgen);
        *Qgen = ((MODELICA_Real) self->Qgen);
        *v = ((MODELICA_Real) self->v);
        *vf0OUT = ((MODELICA_Real) self->vf0OUT);
        *w = ((MODELICA_Real) self->w);
        result = ((MODELICA_Integer) self->ErrorSignals);
    }

    return result;
}

MODELICA_Integer mei_Recalibrate_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void \
    *object
,   /* TUNEABLE */  MODELICA_Real   K0
) {
    ALGOSTRUCT *self = (ALGOSTRUCT *) object;
    MODELICA_Integer result = -1;

    if(self != NULL) {
        self->K0 = (SPE_Real_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c) K0;

        Recalibrate_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(self);

        result = ((MODELICA_Integer) self->ErrorSignals);
    }

    return result;
}

MODELICA_Integer mei_Reinitialize_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void \
    *object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
) {
    ALGOSTRUCT *self = (ALGOSTRUCT *) object;
    MODELICA_Integer result = -1;

    if(self != NULL) {
        self->fault = (0 != fault) ? 1 : 0;
        self->vf = (SPE_Real_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c) vf;

        Reinitialize_H216f2fd6bee4c6cbc88940592d1c21ea8fcaa7b3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(self);

        *Pgen = ((MODELICA_Real) self->Pgen);
        *Qgen = ((MODELICA_Real) self->Qgen);
        *v = ((MODELICA_Real) self->v);
        *vf0OUT = ((MODELICA_Real) self->vf0OUT);
        *w = ((MODELICA_Real) self->w);
        result = ((MODELICA_Integer) self->ErrorSignals);
    }

    return result;
}

#ifdef __cplusplus
}
#endif

/* end of file */
