/*2025-11-13T01:11:09.861Z*/

/**********************************************************************************************************************
 * galec_types.h
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 0.3.0 (beta, internal R&D version)
 **********************************************************************************************************************/

#ifndef GALEC_TYPES_H_H283CD02180511B024B59731032FD3290F8675B29_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED
#define GALEC_TYPES_H_H283CD02180511B024B59731032FD3290F8675B29_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * basic data types
 **********************************************************************************************************************/
typedef unsigned int    Boolean;
#ifndef ESP_true
#define ESP_true           ((Boolean)1)
#endif
#ifndef ESP_false
#define ESP_false          ((Boolean)0)
#endif
typedef signed int      Integer;
typedef float           Real;   /* 32 bits precision */

#define INT_SEL(i,l,ll) i
#define FLT_SEL(f,d,ld) f

/**********************************************************************************************************************
 * signals
 **********************************************************************************************************************/
#include <stdint.h>
typedef unsigned int                                ErrorSignal;
#define ErrorSignal_NONE                            (ErrorSignal)(0u)
#define ErrorSignal_INVALID_ARGUMENT                (ErrorSignal)(1u << 0)
#define ErrorSignal_OVERFLOW                        (ErrorSignal)(1u << 1)
#define ErrorSignal_NAN                             (ErrorSignal)(1u << 2)
#define ErrorSignal_SOLVE_LINEAR_EQUATIONS_FAILED   (ErrorSignal)(1u << 3)
#define ErrorSignal_NO_SOLUTION_FOUND               (ErrorSignal)(1u << 4)
#define ErrorSignal_UNSPECIFIED_ERROR               (ErrorSignal)(1u << 5)

#ifdef __cplusplus
}
#endif

#endif /*  GALEC_TYPES_H_H283CD02180511B024B59731032FD3290F8675B29_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED */
/* end of file */
