/*2026-01-14T21:21:50.288678165Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_BLOCK_HB0CB05F437863E9FECE1A90BB931DBFEB4AC00F3_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H
#define MEI_BLOCK_INTERFACE_BLOCK_HB0CB05F437863E9FECE1A90BB931DBFEB4AC00F3_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

typedef int MODELICA_Boolean;
typedef int MODELICA_Integer;
typedef double MODELICA_Real;

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
/* return new instance */
extern void *mei_Startup_Hb0cb05f437863e9fece1a90bb931dbfeb4ac00f3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c  (void);
/* destroy instance */
extern void  mei_Terminate_Hb0cb05f437863e9fece1a90bb931dbfeb4ac00f3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void* object);
/* perform simulation step */
extern MODELICA_Integer mei_DoStep_Hb0cb05f437863e9fece1a90bb931dbfeb4ac00f3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c  \
     (void* object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
);

/* recalibrate parameters */
extern MODELICA_Integer mei_Recalibrate_Hb0cb05f437863e9fece1a90bb931dbfeb4ac00f3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c \
      (void* object
);

/* reinitialize states and outputs */
extern MODELICA_Integer mei_Reinitialize_Hb0cb05f437863e9fece1a90bb931dbfeb4ac00f3_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c \
      (void* object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_BLOCK_HB0CB05F437863E9FECE1A90BB931DBFEB4AC00F3_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H */
/* end of file */
