/*2026-02-27T16:02:15.282202900Z*/

/**********************************************************************************************************************
 * sii_block_interface.h
 *
 * Single internal instance.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 *
 * with calling convention :
 *   Arguments = global var (block_state_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c)
 *   Ret. type = bool
 *
 * with names :
 *   Init Fcn  = sii_Startup_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Step Fcn  = sii_DoStep_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Recal Fcn = sii_Recalibrate_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Reinit Fcn = sii_Reinitialize_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 **********************************************************************************************************************/

#ifndef SII_BLOCK_INTERFACE_BLOCK_HF39FB1278F8DB8EF2BABEC40D87EE0BEAD042D46_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H
#define SII_BLOCK_INTERFACE_BLOCK_HF39FB1278F8DB8EF2BABEC40D87EE0BEAD042D46_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * code
 **********************************************************************************************************************/
extern bool sii_Startup_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
extern bool sii_DoStep_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
extern bool sii_Recalibrate_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);

extern bool sii_Reinitialize_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
/**********************************************************************************************************************
 * data
 **********************************************************************************************************************/
extern BlockState_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c block_state_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c; \
    /* global memory storage */

#ifdef __cplusplus
}
#endif

#endif /* SII_BLOCK_INTERFACE_BLOCK_HF39FB1278F8DB8EF2BABEC40D87EE0BEAD042D46_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H */
/* end of file */
