/* Linearization */
#include "GenIO4HILinNetwork_model.h"
#if defined(__cplusplus)
extern "C" {
#endif
const char *GenIO4HILinNetwork_linear_model_frame()
{
  return "model linearized_model \"GenIO4HILinNetwork\"\n"
  "  parameter Integer n = 6 \"number of states\";\n"
  "  parameter Integer m = 1 \"number of inputs\";\n"
  "  parameter Integer p = 5 \"number of outputs\";\n"
  "\n"
  "  parameter Real x0[n] = %s;\n"
  "  parameter Real u0[m] = %s;\n"
  "\n"
  "  parameter Real A[n, n] =\n\t[%s];\n\n"
  "  parameter Real B[n, m] =\n\t[%s];\n\n"
  "  parameter Real C[p, n] =\n\t[%s];\n\n"
  "  parameter Real D[p, m] =\n\t[%s];\n\n"
  "\n"
  "  Real x[n](start=x0);\n"
  "  input Real u[m](start=u0);\n"
  "  output Real y[p];\n"
  "\n"
  "  Real 'x_G1.machine.delta' = x[1];\n"
  "  Real 'x_G1.machine.e1d' = x[2];\n"
  "  Real 'x_G1.machine.e1q' = x[3];\n"
  "  Real 'x_G1.machine.e2d' = x[4];\n"
  "  Real 'x_G1.machine.e2q' = x[5];\n"
  "  Real 'x_G1.machine.w' = x[6];\n"
  "  Real 'u_vf' = u[1];\n"
  "  Real 'y_Pgen' = y[1];\n"
  "  Real 'y_Qgen' = y[2];\n"
  "  Real 'y_v' = y[3];\n"
  "  Real 'y_vf0OUT' = y[4];\n"
  "  Real 'y_w' = y[5];\n"
  "equation\n"
  "  der(x) = A * x + B * u;\n"
  "  y = C * x + D * u;\n"
  "end linearized_model;\n";
}
const char *GenIO4HILinNetwork_linear_model_datarecovery_frame()
{
  return "model linearized_model \"GenIO4HILinNetwork\"\n"
  "  parameter Integer n = 6 \"number of states\";\n"
  "  parameter Integer m = 1 \"number of inputs\";\n"
  "  parameter Integer p = 5 \"number of outputs\";\n"
  "  parameter Integer nz = 70 \"data recovery variables\";\n"
  "\n"
  "  parameter Real x0[n] = %s;\n"
  "  parameter Real u0[m] = %s;\n"
  "  parameter Real z0[nz] = %s;\n"
  "\n"
  "  parameter Real A[n, n] =\n\t[%s];\n\n"
  "  parameter Real B[n, m] =\n\t[%s];\n\n"
  "  parameter Real C[p, n] =\n\t[%s];\n\n"
  "  parameter Real D[p, m] =\n\t[%s];\n\n"
  "  parameter Real Cz[nz, n] =\n\t[%s];\n\n"
  "  parameter Real Dz[nz, m] =\n\t[%s];\n\n"
  "\n"
  "  Real x[n](start=x0);\n"
  "  input Real u[m](start=u0);\n"
  "  output Real y[p];\n"
  "  output Real z[nz];\n"
  "\n"
  "  Real 'x_G1.machine.delta' = x[1];\n"
  "  Real 'x_G1.machine.e1d' = x[2];\n"
  "  Real 'x_G1.machine.e1q' = x[3];\n"
  "  Real 'x_G1.machine.e2d' = x[4];\n"
  "  Real 'x_G1.machine.e2q' = x[5];\n"
  "  Real 'x_G1.machine.w' = x[6];\n"
  "  Real 'u_vf' = u[1];\n"
  "  Real 'y_Pgen' = y[1];\n"
  "  Real 'y_Qgen' = y[2];\n"
  "  Real 'y_v' = y[3];\n"
  "  Real 'y_vf0OUT' = y[4];\n"
  "  Real 'y_w' = y[5];\n"
  "  Real 'z_$cse3' = z[1];\n"
  "  Real 'z_$cse4' = z[2];\n"
  "  Real 'z_B1.angle' = z[3];\n"
  "  Real 'z_B1.angleDisplay' = z[4];\n"
  "  Real 'z_B1.p.ii' = z[5];\n"
  "  Real 'z_B1.p.ir' = z[6];\n"
  "  Real 'z_B1.v' = z[7];\n"
  "  Real 'z_B2.angle' = z[8];\n"
  "  Real 'z_B2.angleDisplay' = z[9];\n"
  "  Real 'z_B2.p.ii' = z[10];\n"
  "  Real 'z_B2.p.ir' = z[11];\n"
  "  Real 'z_B2.v' = z[12];\n"
  "  Real 'z_B3.angle' = z[13];\n"
  "  Real 'z_B3.angleDisplay' = z[14];\n"
  "  Real 'z_B3.p.ii' = z[15];\n"
  "  Real 'z_B3.p.ir' = z[16];\n"
  "  Real 'z_B3.v' = z[17];\n"
  "  Real 'z_G1.P' = z[18];\n"
  "  Real 'z_G1.Q' = z[19];\n"
  "  Real 'z_G1.feedbackVf0.y' = z[20];\n"
  "  Real 'z_G1.gainVf0.y' = z[21];\n"
  "  Real 'z_G1.machine.anglev' = z[22];\n"
  "  Real 'z_G1.machine.id' = z[23];\n"
  "  Real 'z_G1.machine.iq' = z[24];\n"
  "  Real 'z_G1.machine.pe' = z[25];\n"
  "  Real 'z_G1.machine.vd' = z[26];\n"
  "  Real 'z_G1.machine.vf_MB' = z[27];\n"
  "  Real 'z_G1.machine.vq' = z[28];\n"
  "  Real 'z_Pgen' = z[29];\n"
  "  Real 'z_Qgen' = z[30];\n"
  "  Real 'z_infiniteBus.P' = z[31];\n"
  "  Real 'z_infiniteBus.Q' = z[32];\n"
  "  Real 'z_infiniteBus.p.ii' = z[33];\n"
  "  Real 'z_infiniteBus.p.ir' = z[34];\n"
  "  Real 'z_infiniteBus.p.vi' = z[35];\n"
  "  Real 'z_infiniteBus.p.vr' = z[36];\n"
  "  Real 'z_pwFault.p.ii' = z[37];\n"
  "  Real 'z_pwFault.p.ir' = z[38];\n"
  "  Real 'z_pwLine1.P12' = z[39];\n"
  "  Real 'z_pwLine1.P21' = z[40];\n"
  "  Real 'z_pwLine1.Q12' = z[41];\n"
  "  Real 'z_pwLine1.Q21' = z[42];\n"
  "  Real 'z_pwLine1.ir.im' = z[43];\n"
  "  Real 'z_pwLine1.ir.re' = z[44];\n"
  "  Real 'z_pwLine1.is.im' = z[45];\n"
  "  Real 'z_pwLine1.is.re' = z[46];\n"
  "  Real 'z_pwLine2.P12' = z[47];\n"
  "  Real 'z_pwLine2.P21' = z[48];\n"
  "  Real 'z_pwLine2.Q12' = z[49];\n"
  "  Real 'z_pwLine2.Q21' = z[50];\n"
  "  Real 'z_pwLine2.ir.im' = z[51];\n"
  "  Real 'z_pwLine2.ir.re' = z[52];\n"
  "  Real 'z_pwLine2.is.im' = z[53];\n"
  "  Real 'z_pwLine2.is.re' = z[54];\n"
  "  Real 'z_pwLine2.vs.im' = z[55];\n"
  "  Real 'z_pwLine2.vs.re' = z[56];\n"
  "  Real 'z_transformer.P12' = z[57];\n"
  "  Real 'z_transformer.P21' = z[58];\n"
  "  Real 'z_transformer.Q12' = z[59];\n"
  "  Real 'z_transformer.Q21' = z[60];\n"
  "  Real 'z_transformer.ir.im' = z[61];\n"
  "  Real 'z_transformer.ir.re' = z[62];\n"
  "  Real 'z_transformer.is.im' = z[63];\n"
  "  Real 'z_transformer.is.re' = z[64];\n"
  "  Real 'z_transformer.vs.im' = z[65];\n"
  "  Real 'z_transformer.vs.re' = z[66];\n"
  "  Real 'z_v' = z[67];\n"
  "  Real 'z_vf' = z[68];\n"
  "  Real 'z_vf0OUT' = z[69];\n"
  "  Real 'z_w' = z[70];\n"
  "equation\n"
  "  der(x) = A * x + B * u;\n"
  "  y = C * x + D * u;\n"
  "  z = Cz * x + Dz * u;\n"
  "end linearized_model;\n";
}
#if defined(__cplusplus)
}
#endif

