/*2025-12-22T23:07:25.560Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 0.3.0 (beta, internal R&D version)
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_HC234CAD58156CCBC9047C71532B337747DEA4C15_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H
#define MEI_BLOCK_INTERFACE_HC234CAD58156CCBC9047C71532B337747DEA4C15_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H

#include <stdlib.h>
#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
extern void *mei_Startup_Hc234cad58156ccbc9047c71532b337747dea4c15_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  (void)    \
         /* return new instance */;
extern void  mei_Terminate_Hc234cad58156ccbc9047c71532b337747dea4c15_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void* object) \
    /* destroy instance */;
extern int   mei_DoStep_Hc234cad58156ccbc9047c71532b337747dea4c15_cb4a8a449b4ada864625ee5a4355578a3aaf08ed   (void* object \
     /* perform simulation step */
,   /* IN */    int fault
,   /* IN */    double  vf
,   /* OUT */   double* Pgen
,   /* OUT */   double* Qgen
,   /* OUT */   double* v
,   /* OUT */   double* vf0OUT
,   /* OUT */   double* w
);

extern int   mei_Recalibrate_Hc234cad58156ccbc9047c71532b337747dea4c15_cb4a8a449b4ada864625ee5a4355578a3aaf08ed   (void* \
    object  /* recalibrate parameters */
,   /* TUNEABLE */  double  K0
);

extern int   mei_Reinitialize_Hc234cad58156ccbc9047c71532b337747dea4c15_cb4a8a449b4ada864625ee5a4355578a3aaf08ed   (void* \
    object  /* reinitialize states and outputs */
,   /* IN */    int fault
,   /* IN */    double  vf
,   /* OUT */   double* Pgen
,   /* OUT */   double* Qgen
,   /* OUT */   double* v
,   /* OUT */   double* vf0OUT
,   /* OUT */   double* w
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_HC234CAD58156CCBC9047C71532B337747DEA4C15_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H */
/* end of file */
