function [env, models, SIG, paperCases] = setupAnalysisEnvironment(scriptDir)
%SETUPANALYSISENVIRONMENT Configure paths and load simulation results.

dymolaRoot = locateDymolaRoot();
addpath(fullfile(dymolaRoot, 'Mfiles'));
addpath(fullfile(dymolaRoot, 'Mfiles', 'dymtools'));
addpath(fullfile(dymolaRoot, 'Mfiles', 'traj'));

repoRoot = fileparts(fileparts(scriptDir));
inputResultsDir = resolveResultsDir(fullfile(repoRoot, 'Modelica', 'work', 'Grid4CHIL_batch_results'));

SIG = struct( ...
    'w',   {{'G4CHIL.G1.machine.w', 'G1.genAVRIOReDesign.machine.w'}}, ...
    'vf',  {{'G4CHIL.vf', 'G1.genAVRIOReDesign.avr.vf'}}, ...
    'pss', {{'pss.vs', 'G1.pss.vs'}}, ...
    'B1',  {{'G4CHIL.B1.v', 'B1.v'}}, ...
    'B2',  {{'G4CHIL.B2.v', 'B2.v'}}, ...
    'B3',  {{'G4CHIL.B3.v', 'B3.v'}});

palette = localHighContrastMap();
markerList = {'o', 's', 'd', '^', 'v', '>', '<', 'p'};

models = struct( ...
    'tag',   {'ReferenceSetup', ...
              'ReferenceSetup_Clocked', ...
              'ReferenceSetup_ExpEuler', ...
              'ReferenceSetup_SiL', ...
              'ReferenceSetup_SiL_FMUs', ...
              'RefSim_ClockedPSS_CT_Plant', ...
              'RefSim_ClockedPSS_CT_Plant_ExpEuler'}, ...
    'label', {'Reference', ...
              'Reference (Clocked)', ...
              'Reference (Exp. Euler)', ...
              'SiL', ...
              'SiL (FMUs)', ...
              'ClockedPSS CT Plant', ...
              'ClockedPSS CT Plant (Exp. Euler)'}, ...
    'style', {'-', '--', ':', '-.', '--', '-', ':'});

for k = 1:numel(models)
    models(k).color = palette(mod(k-1, size(palette, 1)) + 1, :);
    models(k).marker = markerList{mod(k-1, numel(markerList)) + 1};
    models(k).res = [];
end

for k = 1:numel(models)
    matFile = fullfile(inputResultsDir, sprintf('%s_dsres.mat', models(k).tag));
    models(k).res = loadModel(matFile, models(k).tag);
end

paperCases = struct( ...
    'tag', {'RefSim_ClockedPSS_CT_Plant', ...
            'RefSim_ClockedPSS_CT_Plant_ExpEuler', ...
            'ReferenceSetup', ...
            'ReferenceSetup_ExpEuler', ...
            'ReferenceSetup_Clocked'}, ...
    'paperLabel', {'Ref.Sim.DASSL', ...
                   'Ref.Sim.ExpEuler', ...
                   'Ref.Setup', ...
                   'Ref.Setup.ExpEuler', ...
                   'Ref.Setup.Clocked'}, ...
    'shortLabel', {'Sim 1', 'Sim 2', 'Sim 3', 'Sim 4', 'Sim 5'}, ...
    'lineStyle', {'-', '--', ':', '-.', '--'}, ...
    'marker', {'o', 's', 'd', '^', 'v'}, ...
    'itemNumber', num2cell(1:5), ...
    'color', {palette(1,:), palette(2,:), palette(3,:), palette(4,:), palette(5,:)});

env = struct('scriptDir', scriptDir, 'repoRoot', repoRoot, ...
    'inputResultsDir', inputResultsDir, 'palette', palette);
end

function cmap = localHighContrastMap()
% Replace green, yellow and white with page-visible alternatives.
cmap = [ ...
    0.00 0.00 0.00; ...
    0.85 0.10 0.10; ...
    0.90 0.45 0.00; ...
    0.00 0.35 0.85; ...
    0.55 0.20 0.75; ...
    0.00 0.65 0.65; ...
    0.35 0.35 0.35; ...
    0.55 0.27 0.07];
end

function res = loadModel(matFile, tag)
res = [];
if ~isfile(matFile)
    warning('setupAnalysisEnvironment:missingFile', ...
        'Result file not found for %s: %s', tag, matFile);
    return;
end
try
    res = dymload(matFile);
catch ME
    warning('setupAnalysisEnvironment:loadFailed', ...
        'Failed to load %s: %s', tag, ME.message);
end
end

function resultsDir = resolveResultsDir(defaultResultsDir)
resultsDir = defaultResultsDir;
fromEnv = strtrim(getenv('GRID4CHIL_RESULTS_DIR'));
if ~isempty(fromEnv)
    resultsDir = fromEnv;
end
end

function dymolaRoot = locateDymolaRoot()
defaultRoot = fullfile('C:\', 'Program Files', 'Dymola 2026x Refresh 1');
if isfolder(defaultRoot)
    dymolaRoot = defaultRoot;
    return;
end
roots = dir(fullfile('C:\', 'Program Files', 'Dymola*'));
roots = roots([roots.isdir]);
if isempty(roots)
    error('setupAnalysisEnvironment:noDymola', ...
        'No Dymola installation found under C:\\Program Files.');
end
[~, idx] = max([roots.datenum]);
dymolaRoot = fullfile(roots(idx).folder, roots(idx).name);
end
