/*2025-12-22T23:07:27.570Z*/

/**********************************************************************************************************************
 * sii_block_interface.h
 *
 * Single internal instance.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 0.3.0 (beta, internal R&D version)
 *
 * with calling convention :
 *   Arguments = global var (block_state_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c)
 *   Ret. type = Boolean
 *
 * with names :
 *   Init Fcn  = sii_Startup_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Step Fcn  = sii_DoStep_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Recal Fcn = sii_Recalibrate_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 *   Reinit Fcn = sii_Reinitialize_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c
 **********************************************************************************************************************/

#ifndef SII_BLOCK_INTERFACE_HC234CAD58156CCBC9047C71532B337747DEA4C15_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H
#define SII_BLOCK_INTERFACE_HC234CAD58156CCBC9047C71532B337747DEA4C15_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 * code
 **********************************************************************************************************************/
extern Boolean sii_Startup_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
extern Boolean sii_DoStep_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
extern Boolean sii_Recalibrate_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);

extern Boolean sii_Reinitialize_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c(void);
/**********************************************************************************************************************
 * data
 **********************************************************************************************************************/
extern BlockState_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c block_state_Hc234cad58156ccbc9047c71532b337747dea4c15_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c; \
    /* global memory storage */

#ifdef __cplusplus
}
#endif

#endif /* SII_BLOCK_INTERFACE_HC234CAD58156CCBC9047C71532B337747DEA4C15_FBA3E0DFA6C8985B41BCBE3594EE941CE98B740C_H */
/* end of file */
