/*2026-02-27T16:02:12.306976Z*/

/**********************************************************************************************************************
 * mei_block_interface.h
 *
 * Multiple external instances.
 *
 * generated by : dymola-embedded/MEI_SII_CodeGen 1.0.0
 **********************************************************************************************************************/

#ifndef MEI_BLOCK_INTERFACE_BLOCK_HF39FB1278F8DB8EF2BABEC40D87EE0BEAD042D46_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H
#define MEI_BLOCK_INTERFACE_BLOCK_HF39FB1278F8DB8EF2BABEC40D87EE0BEAD042D46_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H

#include "block.h"

/**********************************************************************************************************************
 * public interface
 **********************************************************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

typedef int MODELICA_Boolean;
typedef int MODELICA_Integer;
typedef double MODELICA_Real;

/**********************************************************************************************************************
 * Public Co-simulation API for Dymola
 **********************************************************************************************************************/
/* return new instance */
extern void *mei_Startup_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  (void);
/* destroy instance */
extern void  mei_Terminate_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_cb4a8a449b4ada864625ee5a4355578a3aaf08ed(void* object);
/* perform simulation step */
extern MODELICA_Integer mei_DoStep_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_cb4a8a449b4ada864625ee5a4355578a3aaf08ed  \
     (void* object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
);

/* recalibrate parameters */
extern MODELICA_Integer mei_Recalibrate_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
);

/* reinitialize states and outputs */
extern MODELICA_Integer mei_Reinitialize_Hf39fb1278f8db8ef2babec40d87ee0bead042d46_cb4a8a449b4ada864625ee5a4355578a3aaf08ed \
      (void* object
,   /* IN */    MODELICA_Boolean    fault
,   /* IN */    MODELICA_Real   vf
,   /* OUT */   MODELICA_Real*  Pgen
,   /* OUT */   MODELICA_Real*  Qgen
,   /* OUT */   MODELICA_Real*  v
,   /* OUT */   MODELICA_Real*  vf0OUT
,   /* OUT */   MODELICA_Real*  w
);

#ifdef __cplusplus
}
#endif

#endif /* MEI_BLOCK_INTERFACE_BLOCK_HF39FB1278F8DB8EF2BABEC40D87EE0BEAD042D46_CB4A8A449B4ADA864625EE5A4355578A3AAF08ED_H */
/* end of file */
